- name: Install Prerequisites (Container Runtime)
  hosts: all
  become: yes
  roles:
    # Install Common Software(s) on Master Node and Worker node.
    - Ansible_install_CRIO_Role
    - Ansible_Install_Kubeadm_Kubectl_Kubelet_Linux_Role

- name: install/ Configure Master Node.
  hosts: master
  gather_facts: no
  roles:
  # This role is applied on the master node
  - Ansible_Kubeadm_K8S_Master_Role
  - Ansible_install_CNI_Kubeadm_Role
- name: Join Worker Node to Master Node
  gather_facts: no
  hosts: workers
  roles:
    - Ansible_Worker_Nodes_Role
