# Task For Docker
- name: install Docker
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

# The cgroupfs driver is the default cgroup driver in the kubelet. When the cgroupfs driver is used, the kubelet and the container runtime directly interface with the cgroup filesystem to configure cgroups.

- name: Create Directory for Configuring Docker
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Change cgroup driver from cgroupfs to systemd
  copy:
    dest: '/etc/docker/daemon.json'
    content: |
     {
       "exec-opts": ["native.cgroupdriver=systemd"]
     }
  notify: 
    - daemon reload

- name: Start Docker
  service:
    name: docker
    enabled: yes
    state: restarted
