- name: Add Docker repository
  yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    gpgcheck: no
    description: Docker Package from Yum Repos
- name: install Docker Engine
  shell: sudo yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
